### ISSUE TITLE
Eh illegal copy with JACK???

### ISSUE THREAD

**Issue by DeafMan1983** [jean-knapp/xblah-modding-tool-public#14]
Hello I found JACK in release.7z

![image](https://github.com/jean-knapp/xblah-modding-tool-public/assets/57066679/e737e8b5-8b73-4ab9-bf40-3bcb898b6c54)

That is not allowed because you upload with Steam-Version JACK.
https://store.steampowered.com/app/496450/JACK/

Please remove copy of JACK but people think badly. Please remove cause copyright. Thank you!

**Comment by jean-knapp** [comment]
They've published an updated version of Jack. In their website, they state "J.A.C.K. is donationware, that means a freely distributed software developed by the voluntary contributions of users.". Neither in their readme or in their website, they state they are against reuploads. This repository is public and anyone can download it. This tool by no means put J.A.C.K. behind a paywall. It just helps users to automatically configure it.

I've had this same issue with Hammer++, and the author requested me that the tool download the program instead of distribute it. If you are the author of J.A.C.K. and prefer it this way, let me know.

**Comment by DeafMan1983** [comment]
Lol I am not author of Jack. I will respect you but I checked in your website that's why old version of Jack but it is ok. I am sorry for hesitation.  Have nice day/night!
